### ISSUE TITLE
Make Vue string literals/ labels translatable

### ISSUE THREAD

**Issue by agritheory** [agritheory/approvals#36]
![image](https://github.com/agritheory/approvals/assets/18033666/83cc8de9-fd08-402b-bb1a-e9c21ce8e74a)

I tried to do this but couldn't figure out how to do the types.

**Comment by Alchez** [comment]
@agritheory I was able to add typings, but I wasn't able to actually use the `__` global function for translating the text. Do you have a snippet for that?

**Comment by agritheory** [comment]
@Alchez I don't but you could try the `computed` / `unref` pattern I used in Check Run
